name: Bug report
description: Create a bug report to help improve containerd
labels: kind/bug
body:
  - type: markdown
    attributes:
      value: |
        If you are reporting a new issue, make sure that we do not have any duplicates
        already open. You can ensure this by searching the issue list for this
        repository. If there is a duplicate, please close your issue and add a comment
        to the existing issue instead.

        Tips:

        * If containerd gets stuck on something and enables debug socket, `ctr pprof goroutines`
          dumps the golang stack of containerd, which is helpful! If containerd runs
          without debug socket, `kill -SIGUSR1 $(pidof containerd)` also dumps the stack
          as well.

        * If there is something about running containerd, like consuming more CPU resources,
          `ctr pprof` subcommands will help you to get some useful profiles. Enable debug
          socket makes life easier.

  - type: textarea
    attributes:
      label: Description
      description: |
        Briefly describe the problem you are having in a few paragraphs.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce the issue
      value: |
        1.
        2.
        3.

  - type: textarea
    attributes:
      label: Describe the results you received and expected
    validations:
      required: true

  - type: input
    attributes:
      label: What version of containerd are you using?
      placeholder: $ containerd --version
    validations:
      required: true

  - type: textarea
    attributes:
      label: Any other relevant information
      description: |
        runc version, CRI configuration, OS/Kernel version, etc.
        Use the following commands:
        $ runc --version
        $ crictl info
        $ uname -a

  - type: textarea
    attributes:
      label: Show configuration if it is related to CRI plugin.
