# commit to be tagged for new release
commit = "HEAD"

project_name = "containerd"
github_repo = "containerd/containerd"

# previous release
previous = "v1.0.0-beta.2"

pre_release = true

preface = """\
After rounding out the feature set in beta.2, we have taken a number of stability fixes.

This release contains mostly bug fixes, code cleanup and improvements to useability of
the client and ctr tool."""

# notable prs to include in the release notes, 1234 is the pr number
[notes]

  [notes.ctr]
  title= "`ctr` makeover"
  description = """\
`ctr` is getting a ~makeover~! The end goal is for commands to be consistent and scoped.
Most notably:
- `push`, `pull` are now `images` subcommands: `ctr images push`, `ctr images pull`
- `fetch`, `fetch-object`, and `push-object` are `content` subcommands
- `rootfs unpack` is now `snapshot unpack`
- `apply` no longer exists. RIP"""



[breaking]
